### PR TITLE
Сhange type of the distance field in a Gap line to int

### LINKED ISSUE #61: [GFA2] Why is distance in Gap line is 'pos' instead of 'int'
Hi!
Could you clarify why the distance field in a G-line should be of type `pos` rather than `int` according to the Grammar section of the [specification](https://github.com/GFA-spec/GFA-spec/blob/master/GFA2.md)? Is that a mistake?
Thanks!

### PR DESCRIPTION
**Pull request by eshcherbin**
I feel like the distance field in a G-line should be of type `pos` rather than `int`.
Resolves #61.

### CODE REVIEW

**Comment by sjackman** [comment]
I agree.
@thegenemyers Should the distance filed of the gap `G` record be `int` rather than `pos`?

**Comment by ggonnella** [comment]
I agree

**Comment by sjackman** [comment]
This proposal has achieved the required quorum of three votes. We'll wait until Mon 2016-06-12 for additional votes.

**Comment by eshcherbin** [comment]
@sjackman I believe this proposal could be merged, couldn't it?

**Comment by sjackman** [comment]
Yes, thanks for the reminder, Egor. Merged!

**Comment by thegenemyers** [comment]
Belated response, but yes, should be int.  -- G

**Comment by sjackman** [comment]
Thanks for the confirmation, Gene.

**Pull request merged**
