### PR TITLE
Add GfaViz to the list of GFA2 implementations

### PR DESCRIPTION
**Pull request by ggonnella**

### CODE REVIEW

**Comment by sjackman** [comment]
> GfaViz: Flexible and interactive visualization of GFA sequence graphs. Bioinformatics. Accepted for publication (2018)

Congratulations!

**Comment by sjackman** [comment]
Could you please add GfaViz to the list of GFA1 implementations?

**Comment by sjackman** [comment]
> ggonnella/gfaviz
forked from niehus/gfaviz

Which is the canonical repository, ggonnella/gfaviz or niehus/gfaviz? If it's ggonnella, could you please delete the repo `niehus`? You can transfer the issues if you're concerned about losing old issues. Homebrew has a policy against packaging forks.

**Comment by sjackman** [comment]
I see that `ggonnella/gfaviz` has no issues. In that case, you may prefer to instead delete `ggonnella/gfaviz` and then transfer ownership of the repo `niehus/gfaviz` to `ggonnella`.

**Comment by sjackman** [comment]
Once you've sorted out ownership of the repo, could you please tag a stable `1.0.0` release?

**Comment by sjackman** [comment]
I've opened issues https://github.com/niehus/gfaviz/issues/57 and https://github.com/niehus/gfaviz/issues/58 to address packaging.

**Comment by ggonnella** [comment]
Hi Shaun, we decided to consider as canonical ggonnella/gfaviz as it is more likely that I will continue the work on it. I will have a look on how to transfer the issues and delete niehus/gfaviz.

**Comment by ggonnella** [comment]
> Could you please add GfaViz to the list of GFA1 implementations?

should software implementing both appear in both lists?

**Comment by sjackman** [comment]
>> Could you please add GfaViz to the list of GFA1 implementations?
> should software implementing both appear in both lists?

Yes. It hasn't happened yet, but it's possible (perhaps unlikely) that a tool could support GFA2 and not GFA1.

**Comment by sjackman** [comment]
> Hi Shaun, we decided to consider as canonical ggonnella/gfaviz as it is more likely that I will continue the work on it. I will have a look on how to transfer the issues and delete niehus/gfaviz.

The easiest is to push your commits to `niehus/gfaviz`, then delete the repo `ggonnella/gfaviz`, and transfer ownership of `niehus/gfaviz` to `ggonnella/gfaviz` in https://github.com/niehus/gfaviz/settings `Transfer ownership`. I've used this tool a number of times, and it works great. The old repo will also seamlessly forward to the new one.

**Pull request closed without merging**
