### PR TITLE
Define walk line in GFA1

### PR DESCRIPTION
**Pull request by lh3**
This PR adds a new type of line, walk or W-line, to GFA1. It is similar to P-line but specialized for pangenome graphs with fixed fields for sample name, haplotype index and sequence name. The Human Pangenome Project may use this addition to encode human graphs.

Please don't merge. There are still details to be fleshed out.

### CODE REVIEW

**Comment by lh3** [comment]
Added the SeqStart and SeqEnd fields.

**Comment by mlin** [comment]
How about allowing a Walk to *include* a Path, as a shorthand for a frequent substring (haplotype)? I don't have a strong intuition for whether this would buy a worthwhile intermediate space savings short of going full GBWT.

**Comment by lh3** [comment]
Bump!

@mlin Sorry that I missed your comment. I think putting path and walk together increases the complexity. I would prefer a simpler format.

**Comment by mlin** [comment]
I was working on adding W-lines to gfabase, hit the following roadbump with SeqStart/SeqEnd: suppose user is asking to slice/subset the GFA to a specific region or series of bubbles. In some common cases, it'd be reasonable+useful to provide substrings of the Walks (namely, when a Walk has exactly one substring whose segments are all included in the subgraph). It's then however not straightforward to set SeqStart and SeqEnd in the sub-GFA:

1. If we copy them as-is then they'd be misleading.
2. We could attempt to recalculate them based on the lengths of the flanking excluded segments, but this seems dicey if the original sequence may have indels wrt the graph segments (not represented in the graph)
3. They can't (as of this diff) be left missing.

If we could set them to missing, then I can always pile extra info in tags.

**Comment by lh3** [comment]
Bump

**Comment by ekg** [comment]
This has been implemented in VG, and so it's being used by a few methods there. We should probably merge to avoid confusion. 

IMO: it would be ideal if the specification chose one way to represent paths. The P lines have a lot of tools that work with them, making a complete change awkward. However, because the semantic content doesn't really change, it seems irrelevant if we have one, two, or many ways of writing paths. But, it will cause compatibility issues that could be avoided by simply using the P lines and adding metadata and annotations to them with tags. These problems will certainly confuse users. That all said it will be worse if it isn't in the spec.

**Comment by glennhickey** [comment]
I am resurrecting this as we will need it in order to submit some of the [Year-1 HPRC graphs](https://github.com/human-pangenomics/hpp_pangenome_resources/) to NCBI, and as @ekg mentions (along with solid points against!) there is now support for it in VG

**Comment by glennhickey** [comment]
@lh3 and others: Do you think this is ready to merge?  I have two questions
* (this is from Valerie Schneider):  Is there a version number to go along with this?  Something like GFA 1.1?
* Do you have an opinion on @mlin's request to make the start/stop optional?  I think allowing "*" for these fields is reasonable.

**Comment by ekg** [comment]
This PR and its discussion proposed to add W-lines to GFAv1. I supported this. However, as merged it introduced v1.1 and added W-lines there.

I have proposed a resolution to this here that further clarifies what is going on with the two path formats: https://github.com/GFA-spec/GFA-spec/pull/110

Unfortunately, I missed the call where Valerie asked if it made sense to add v1.1, @glennhickey 's comment 23 days ago, and also @lh3's commits 8 days ago.

We can simply call GFAs with W-lines v1.0. The distinction in the input masking and graph generation procedure should be given in other metadata added to genbank submissions. Existing tools ignore namespaces they don't understand. If we make this specific in the specification, then there won't be problems in the future with user or application-level extensions like the W-line.

**Comment by lh3** [comment]
Although I didn't initially propose to bump the version number, I actually like this idea. W-line aims to be the standard way to encode sequences in pangenome graphs because P-line can't explicitly encode sample information. For graphs without overlaps, W-line is a more flexible version of P-line and can replace it. I disagree with your description in the other PR.

**Comment by heuermh** [comment]
The community using GFA version 1.0 is rather large and doesn't seem to be fully represented here on this pull request.  It feels to me like a decision to cut a new version 1.1 needs more discussion.

**Comment by glennhickey** [comment]
@heuermh This sounds fair enough.  I don't think we ever expected the version number to be so controversial, as it leaves the existing 1.0 spec entirely untouched, but that particular change was indeed merged in rather quickly.  @lh3 What do you think about re-opening this?  

It would be nice to hear more from the GFA community here.

**Comment by lh3** [comment]
Adding a new line type can justify a version bump. Most GFAv1 users are working on assembly and are not affected by the new W-line or the version bump.

**Pull request merged**
