### PR TITLE
Fix example and typos

### PR DESCRIPTION
**Pull request by ggonnella**
Fixes https://github.com/GFA-spec/GFA-spec/issues/64

### CODE REVIEW

**Comment by sjackman** [comment]
:+1: Thanks, @ggonnella. Awaiting one more vote to meet the quorum of 3 votes.
@eshcherbin Egor, care to vote?

**Comment by eshcherbin** [comment]
:+1:
I agree.

**Comment by sjackman** [comment]
Thanks! I'll wait until Tuesday 2017-07-04 to merge this PR, to wait for more votes. Please comment here if I forget.

**Comment by sjackman** [comment]
Merged. Thanks again for your contribution to the GFA spec, Giorgio! :tada:

**Pull request merged**
